### ISSUE TITLE
http://logstash:31311 -> http://localhost:31311

### ISSUE THREAD

**Issue by hhko** [FantasticFiasco/serilog-sinks-http-sample-elastic-stack#78]
**Describe the bug**
The URL `http://logstash:31311`  is written incorrectly.
https://github.com/FantasticFiasco/serilog-sinks-http-sample-elastic-stack/blob/master/serilog/Program.cs#L16

**To Reproduce**
In my case, The URL `http://localhost:31311` works normally.

**Comment by FantasticFiasco** [comment]
Hi @hhko and welcome!

I'm guessing that you're running the console application in your terminal, is that correct? In that case you are correct using `localhost` (or `127.0.0.1`), but if you run the console application in Docker, `logstash` is correct since Docker will resolve the hostname to the IP of the container.

Am I correct in assuming that you run the console application in your terminal?

**Comment by hhko** [comment]
Hi @FantasticFiasco 
You are right. I'm running the console application in my terminal.
I think, it would be nice to add more detailed explanations about how to run `serilog example app` in the README.md file.

Thank you.

**Comment by FantasticFiasco** [comment]
I agree, you are correct. How about adding information in README.md, but perhaps also in the console application. What do you think about changing `Program.cs` to look something like this?

```csharp
static void Main()
{
  // Use the following request URI if you're running this console application in a Docker container
  var requestUri = "http://logstash:31311";

  // Use the following request URI if you're running this console application locally
  //var requestUri = "http://localhost:31311";

  ILogger logger = new LoggerConfiguration()
    .WriteTo.DurableHttpUsingFileSizeRolledBuffers(
      requestUri: requestUri,
      batchFormatter: new ArrayBatchFormatter())
    .WriteTo.Console()
    .CreateLogger()
    .ForContext<Program>();
}
```

Is updating README.md and `Program.cs` a contribution you would like to make? If not I would be happy to make the changes.

**Comment by hhko** [comment]
@FantasticFiasco

Thank you for your consideration of the above point.

**Comment by FantasticFiasco** [comment]
I've updated README.md and added a note in `Program.cs`. Thank you very much for the feedback!
